import {
  Home,
  CheckSquare,
  FileText,
  ShoppingCart,
  Heart,
  Wallet,
  Moon,
  Lightbulb,
  DoorClosed,
  DoorOpen,
} from 'lucide-react'

export const sidebarItems = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: Home,
    href: '/dashboard',
    color: 'text-indigo-500',
    bg: 'bg-indigo-100',
    indicator: 'bg-indigo-500',
  },
  {
    id: 'tasks',
    label: 'Tarefas',
    icon: CheckSquare,
    href: '/dashboard/tasks',
    color: 'text-blue-500',
    bg: 'bg-blue-100/30',
    indicator: 'bg-blue-500',
  },
  {
    id: 'notes',
    label: 'Notas Rápidas',
    icon: FileText,
    href: '/dashboard/notes',
    color: 'text-orange-500',
    bg: 'bg-orange-100',
    indicator: 'bg-orange-500',
  },
  {
    id: 'shopping',
    label: 'Compras',
    icon: ShoppingCart,
    href: '/dashboard/shopping',
    color: 'text-emerald-500',
    bg: 'bg-emerald-100',
    indicator: 'bg-emerald-500',
  },
  {
    id: 'health',
    label: 'Saúde',
    icon: Heart,
    href: '/dashboard/health',
    color: 'text-rose-500',
    bg: 'bg-rose-100',
    indicator: 'bg-rose-500',
  },
  {
    id: 'finance',
    label: 'Finanças',
    icon: Wallet,
    href: '/dashboard/finance',
    color: 'text-violet-500',
    bg: 'bg-violet-100',
    indicator: 'bg-violet-500',
  },
  {
    id: 'sleep',
    label: 'Sono',
    icon: Moon,
    href: '/dashboard/sleep',
    color: 'text-sky-500',
    bg: 'bg-sky-100',
    indicator: 'bg-sky-500',
  },
  {
    id: 'ideas',
    label: 'Ideias',
    icon: Lightbulb,
    href: '/dashboard/ideas',
    color: 'text-amber-500',
    bg: 'bg-amber-100',
    indicator: 'bg-amber-500',
  },
  {
    id: 'Sair',
    label: 'Sair',
    icon: DoorOpen,
    href: "",
    color: 'text-amber-500',
    bg: 'bg-amber-100',
    indicator: 'bg-amber-500',
  }
]
